import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  fallback: ["Arail", "sans serif"],
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Jérôme LEFEUVRE - Développeur Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={inter.className} id="test">
        {children}
      </body>
    </html>
  );
}
